import { useEffect, useMemo, useRef, useState } from 'react'
import type { ChangeEvent, FormEvent, ReactNode } from 'react'
import { Map as MapLibreMap, NavigationControl, Popup, type GeoJSONSource, type StyleSpecification } from 'maplibre-gl'
import type { Feature, FeatureCollection, LineString, Point, Polygon } from 'geojson'
import 'maplibre-gl/dist/maplibre-gl.css'
import { getDocument, GlobalWorkerOptions } from 'pdfjs-dist'
import pdfWorkerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url'
import { createWorker } from 'tesseract.js'
import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Bell, BrainCircuit, ChevronDown, CircleHelp, Crosshair, Database, FileScan, FileText, Gauge, Layers3, MapPinned, Menu, Network, PanelLeftClose, Search, Send, Settings2, Sparkles, Target, Upload, X, Zap } from 'lucide-react'

type View = 'command' | 'documents' | 'embeddings' | 'prediction'
type Tone = 'critical' | 'warning' | 'stable'
type Well = { id: string; x: number; y: number; depth: string; distance: string; state: 'active' | 'offset'; risk?: Tone }
type Block = { id: string; label: string; x: number; y: number; w: number; h: number; tone: 'cyan' | 'amber' | 'coral' }

GlobalWorkerOptions.workerSrc = pdfWorkerUrl
let activePreviewUrl = '/NWIS_DDR_A17_DEMO.pdf'

const ddrRecord = {
  wellName: 'A-17 / Barail North', reportNo: 'Day 14', latitude: 26.123456, longitude: 97.654321,
  currentMd: 2853, currentTvd: 2418, formation: 'Barail - Upper sandstone', mudWeight: '1.35 SG',
  events: [
    { time: '19:48', title: 'Partial returns', depth: 2805, severity: 'High', detail: 'Reduce ECD; maintain circulation.' },
    { time: '20:20', title: 'High flow deviation', depth: 2818, severity: 'Medium', detail: 'Flow check against A-08 behaviour.' },
    { time: '17:35', title: 'NPT - hydraulic leak', depth: 2831, severity: 'Low', detail: 'Repair iron roughneck; record 2.5 h NPT.' },
  ],
  offsets: [{ id: 'A-08', separation: '0.9 km', note: 'Loss correlation' }, { id: 'A-12', separation: '1.8 km', note: 'Pressure correlation' }, { id: 'A-21', separation: '2.6 km', note: 'Directional context' }],
}

const wells: Well[] = [
  { id: 'A-17', x: 50, y: 57, depth: `${ddrRecord.currentMd.toLocaleString()} m`, distance: '0 km', state: 'active' },
  { id: 'A-12', x: 59, y: 16, depth: '2,311 m', distance: '4.8 km', state: 'offset', risk: 'stable' },
  { id: 'A-21', x: 78, y: 29, depth: '2,902 m', distance: '5.6 km', state: 'offset', risk: 'warning' },
  { id: 'A-08', x: 28, y: 34, depth: '2,626 m', distance: '3.9 km', state: 'offset', risk: 'critical' },
  { id: 'A-03', x: 17, y: 53, depth: '2,150 m', distance: '6.2 km', state: 'offset', risk: 'stable' },
  { id: 'A-19', x: 84, y: 52, depth: '2,734 m', distance: '4.1 km', state: 'offset', risk: 'warning' },
  { id: 'A-15', x: 79, y: 75, depth: '2,601 m', distance: '5.0 km', state: 'offset', risk: 'critical' },
  { id: 'A-07', x: 43, y: 88, depth: '2,205 m', distance: '3.6 km', state: 'offset', risk: 'stable' },
  { id: 'A-10', x: 22, y: 78, depth: '2,478 m', distance: '4.4 km', state: 'offset', risk: 'warning' },
]
const blocks: Block[] = [
  { id: 'b1', label: 'TITLE', x: 9, y: 7, w: 39, h: 10, tone: 'cyan' }, { id: 'b2', label: 'WELL / DATE', x: 55, y: 7, w: 35, h: 12, tone: 'amber' },
  { id: 'b3', label: 'OPS SUMMARY', x: 7, y: 23, w: 53, h: 18, tone: 'cyan' }, { id: 'b4', label: 'METRICS TABLE', x: 63, y: 24, w: 29, h: 24, tone: 'amber' },
  { id: 'b5', label: 'LITHOLOGY', x: 7, y: 45, w: 54, h: 18, tone: 'cyan' }, { id: 'b6', label: 'DRILLING NOTE', x: 7, y: 67, w: 85, h: 17, tone: 'amber' },
]
const embeddingPoints = [[15, 67, 'cyan'], [20, 58, 'cyan'], [24, 74, 'cyan'], [28, 62, 'cyan'], [31, 80, 'cyan'], [42, 32, 'amber'], [47, 38, 'amber'], [52, 28, 'amber'], [55, 43, 'amber'], [60, 35, 'amber'], [74, 64, 'coral'], [79, 55, 'coral'], [84, 72, 'coral'], [89, 61, 'coral'], [83, 82, 'coral'], [65, 16, 'slate'], [71, 23, 'slate'], [77, 14, 'slate'], [69, 31, 'slate']] as const
const center: [number, number] = [ddrRecord.longitude, ddrRecord.latitude]
const mapStyle: StyleSpecification = { version: 8, sources: {}, layers: [{ id: 'background', type: 'background', paint: { 'background-color': '#edf7f5' } }] }
function circlePolygon(radiusKm: number) { const pts: [number, number][] = []; for (let i = 0; i <= 64; i += 1) { const a = (i / 64) * Math.PI * 2; pts.push([center[0] + (radiusKm / 98) * Math.cos(a), center[1] + (radiusKm / 111) * Math.sin(a)]) } return { type: 'Feature', properties: {}, geometry: { type: 'Polygon', coordinates: [pts] } } as Feature<Polygon> }
function geojsonWells(visible: Well[]) { return { type: 'FeatureCollection', features: visible.map((well) => ({ type: 'Feature', properties: { id: well.id, depth: well.depth, state: well.state }, geometry: { type: 'Point', coordinates: [center[0] + (well.x - 50) / 50, center[1] + (50 - well.y) / 50] } })) } as FeatureCollection<Point> }
function geojsonTrajectories(visible: Well[]) { return { type: 'FeatureCollection', features: visible.filter((w) => w.id !== 'A-17').map((w) => ({ type: 'Feature', properties: {}, geometry: { type: 'LineString', coordinates: [center, [center[0] + (w.x - 50) / 75, center[1] + (50 - w.y) / 75], [center[0] + (w.x - 50) / 50, center[1] + (50 - w.y) / 50]] } })) } as FeatureCollection<LineString> }

async function parseDdrPdf(file: File, onProgress: (value: number) => void) {
  const document = await getDocument({ data: await file.arrayBuffer() }).promise
  let extractedText = ''
  for (let pageNumber = 1; pageNumber <= document.numPages; pageNumber += 1) {
    const page = await document.getPage(pageNumber)
    const content = await page.getTextContent()
    const pageText = content.items.map((item) => ('str' in item ? item.str : '')).join(' ')
    extractedText += ` ${pageText}`
    onProgress(Math.round((pageNumber / document.numPages) * 55))
    if (pageText.trim().length < 80) {
      const viewport = page.getViewport({ scale: 1.7 })
      const canvas = window.document.createElement('canvas')
      canvas.width = viewport.width; canvas.height = viewport.height
      const context = canvas.getContext('2d')
      if (context) {
        await page.render({ canvas, canvasContext: context, viewport }).promise
        const worker = await createWorker('eng')
        const result = await worker.recognize(canvas)
        extractedText += ` ${result.data.text}`
        await worker.terminate()
      }
    }
  }
  const md = extractedText.match(/Current\s+MD\s*(?:\(m\)|\(ft\))?\s*[:]?\s*([\d,]+)/i)
  const lat = extractedText.match(/Latitude\s*:\s*([\d.]+)/i)
  const lon = extractedText.match(/Longitude\s*:\s*([\d.]+)/i)
  const structured = await fetch('http://localhost:8787/api/structure-ddr', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ text: extractedText }) }).then((response) => response.ok ? response.json() : null).catch(() => null)
  return { pages: document.numPages, text: extractedText, md: md ? Number(md[1].replace(/,/g, '')) : ddrRecord.currentMd, lat: lat?.[1], lon: lon?.[1], structured }
}

function RealMap({ radius, onSelect }: { radius: number; onSelect: (id: string) => void }) {
  const containerRef = useRef<HTMLDivElement>(null); const mapRef = useRef<MapLibreMap | null>(null)
  const visible = useMemo(() => wells.filter((well) => well.state === 'active' || Number.parseFloat(well.distance) <= radius), [radius])
  useEffect(() => {
    if (!containerRef.current || mapRef.current) return
    const map = new MapLibreMap({ container: containerRef.current, style: mapStyle, center, zoom: 9.3, attributionControl: false }); map.addControl(new NavigationControl({ showCompass: true }), 'top-right')
    map.on('load', () => {
      map.addSource('osm', { type: 'raster', tiles: ['https://tile.openstreetmap.org/{z}/{x}/{y}.png'], tileSize: 256, maxzoom: 19, attribution: '© OpenStreetMap contributors' })
      map.addLayer({ id: 'osm-base', type: 'raster', source: 'osm', paint: { 'raster-opacity': .34, 'raster-saturation': -.65, 'raster-contrast': -.08 } })
      map.addSource('radius', { type: 'geojson', data: circlePolygon(radius) }); map.addLayer({ id: 'radius-fill', type: 'fill', source: 'radius', paint: { 'fill-color': '#e86b4d', 'fill-opacity': .06 } }); map.addLayer({ id: 'radius-line', type: 'line', source: 'radius', paint: { 'line-color': '#e86b4d', 'line-width': 1, 'line-dasharray': [2, 2] } })
      map.addSource('trajectories', { type: 'geojson', data: geojsonTrajectories(visible) }); map.addLayer({ id: 'trajectories-line', type: 'line', source: 'trajectories', paint: { 'line-color': '#74bdb7', 'line-width': 2, 'line-opacity': .7 } })
      map.addSource('wells', { type: 'geojson', data: geojsonWells(visible) }); map.addLayer({ id: 'well-points', type: 'circle', source: 'wells', paint: { 'circle-radius': ['case', ['==', ['get', 'state'], 'active'], 9, 5], 'circle-color': ['case', ['==', ['get', 'state'], 'active'], '#e86b4d', '#55b8b2'], 'circle-stroke-color': '#fff', 'circle-stroke-width': 2 } }); map.addLayer({ id: 'well-labels', type: 'symbol', source: 'wells', layout: { 'text-field': ['get', 'id'], 'text-offset': [0, 1.2], 'text-size': 11 }, paint: { 'text-color': '#355a57', 'text-halo-color': '#edf7f5', 'text-halo-width': 1.2 } })
      map.on('click', 'well-points', (event) => { const feature = event.features?.[0]; const id = feature?.properties?.id; if (!id) return; onSelect(id); const point = feature.geometry as Point; new Popup({ closeButton: false, offset: 10 }).setLngLat(point.coordinates as [number, number]).setHTML(`<strong>${id}</strong><br/><span>${feature.properties?.depth}</span>`).addTo(map) }); map.on('mouseenter', 'well-points', () => { map.getCanvas().style.cursor = 'pointer' }); map.on('mouseleave', 'well-points', () => { map.getCanvas().style.cursor = '' })
    }); const resizeObserver = new ResizeObserver(() => map.resize()); resizeObserver.observe(containerRef.current); requestAnimationFrame(() => map.resize()); mapRef.current = map; return () => { resizeObserver.disconnect(); map.remove(); mapRef.current = null }
  }, [])
  useEffect(() => { const map = mapRef.current; if (!map || !map.isStyleLoaded()) return; (map.getSource('radius') as GeoJSONSource | undefined)?.setData(circlePolygon(radius)); (map.getSource('wells') as GeoJSONSource | undefined)?.setData(geojsonWells(visible)); (map.getSource('trajectories') as GeoJSONSource | undefined)?.setData(geojsonTrajectories(visible)) }, [radius, visible])
  return <div className="real-map-wrap"><div ref={containerRef} className="real-map" /><div className="map-overlay-title">LIVE FIELD MAP <span>• {visible.length} WELLS</span></div><aside className="map-ddr-preview"><b><FileText size={12} /> DDR LIVE INGEST</b><span>{ddrRecord.wellName}</span><small>{ddrRecord.latitude.toFixed(6)} N · {ddrRecord.longitude.toFixed(6)} E</small><strong>{ddrRecord.currentMd.toLocaleString()} m · {ddrRecord.formation}</strong><em>⚠ {ddrRecord.events[0].title} @ {ddrRecord.events[0].depth.toLocaleString()} m</em></aside><div className="map-legend compact"><span><i className="legend-dot cyan" />ACTIVE WELL</span><span><i className="legend-dot hollow" />OFFSET WELL</span><span><i className="legend-dash" />RADIUS ZONE</span></div></div>
}

export default function App() {
  const [view, setView] = useState<View>('command'); const [radius, setRadius] = useState(3); const [selectedWell, setSelectedWell] = useState('A-17'); const [selectedEvent, setSelectedEvent] = useState('Partial returns'); const [progress, setProgress] = useState(100); const [processing, setProcessing] = useState(false); const [telemetry, setTelemetry] = useState(ddrRecord.currentMd); const [question, setQuestion] = useState(''); const [prediction, setPrediction] = useState(false); const [uploadName, setUploadName] = useState('NWIS_DDR_A17_DEMO.pdf'); const [sidebarOpen, setSidebarOpen] = useState(true); const [ocrStatus, setOcrStatus] = useState('Indexed demo DDR · 2 pages · 18 operational entities'); const [parsedPages, setParsedPages] = useState(2); const [previewUrl, setPreviewUrl] = useState('/NWIS_DDR_A17_DEMO.pdf')
  useEffect(() => { const timer = window.setInterval(() => setTelemetry((value) => value >= 2864 ? 2846 : value + 1), 1800); return () => window.clearInterval(timer) }, [])
  async function handleUpload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; activePreviewUrl = URL.createObjectURL(file); setPreviewUrl(activePreviewUrl); setUploadName(file.name); setProgress(4); setProcessing(true); setOcrStatus('Opening PDF and queuing page 1…'); setView('documents'); try { const parsed = await parseDdrPdf(file, (value) => { setProgress(value); setOcrStatus(`Extracting page content · ${value}%`) }); setParsedPages(parsed.pages); setTelemetry(parsed.md); setOcrStatus(`OCR + PDF text complete · ${parsed.pages} pages · ${Math.min(24, parsed.text.trim().split(/\s+/).length)} entities linked`); setProgress(100) } catch (error) { setOcrStatus(`Parsing failed: ${error instanceof Error ? error.message : 'unsupported document'}`); setProgress(0) } finally { setProcessing(false); event.target.value = '' } }
  function askPrediction(event: FormEvent) { event.preventDefault(); if (question.trim()) setPrediction(true) }
  function renderView() {
    if (view === 'documents') return <div className="view-grid documents-view"><div className="panel document-panel"><DocumentPanel processing={processing} progress={progress} ocrStatus={ocrStatus} parsedPages={parsedPages} /></div><div className="panel activity-panel"><StreamPanel ocrStatus={ocrStatus} /></div></div>
    if (view === 'embeddings') return <div className="view-grid embeddings-view"><div className="panel embeddings-panel"><EmbeddingPanel selectedEvent={selectedEvent} setSelectedEvent={setSelectedEvent} /></div><div className="panel panel-copy"><PanelHeader icon={<MapPinned size={16} />} title="LINKED WELL CONTEXT" meta="BARAIL / 0–8 KM" /><h2>Evidence clusters become operational context.</h2><p>Select a point to trace its source passage, well, and formation. The same selection is reflected on the field map and depth correlation.</p><div className="linked-well-list">{wells.slice(0, 5).map((well) => <button key={well.id} className={selectedWell === well.id ? 'selected' : ''} onClick={() => setSelectedWell(well.id)}><span>{well.id}</span><small>{well.depth} · {well.distance}</small><ArrowUpRight size={14} /></button>)}</div></div></div>
    if (view === 'prediction') return <div className="view-grid prediction-view"><div className="panel prediction-panel large"><PredictionPanel prediction={prediction} setPrediction={setPrediction} question={question} setQuestion={setQuestion} askPrediction={askPrediction} /></div><div className="panel panel-copy"><PanelHeader icon={<Bell size={16} />} title="ALERT LOG" meta="LAST 60 MIN" /><div className="alert-log"><span><b>09:41</b> Partial returns @ {telemetry} m</span><span><b>09:35</b> High flow deviation</span><span><b>09:21</b> Barail formation top reached</span></div><button className="coral-action" onClick={() => setView('documents')}>OPEN SUPPORTING DOCUMENTS <ArrowUpRight size={14} /></button></div></div>
    return <><div className="hero-grid"><div className="panel map-panel"><PanelHeader icon={<MapPinned size={16} />} title="NEARBY WELLS MAP" meta={`${wells.filter((well) => well.state === 'active' || Number.parseFloat(well.distance) <= radius).length} WELLS / ${radius}.0 KM`} /><div className="map-toolbar"><button className="icon-button" aria-label="Center active well"><Crosshair size={15} /></button><button className="icon-button" aria-label="Toggle layers"><Layers3 size={15} /></button><label className="radius-control">RADIUS <input type="range" min="1" max="8" value={radius} onChange={(event) => setRadius(Number(event.target.value))} /><strong>{radius}.0 km</strong></label></div><RealMap radius={radius} onSelect={setSelectedWell} /></div><div className="panel depth-panel"><DepthPanel telemetry={telemetry} /></div><div className="panel document-panel"><DocumentPanel processing={processing} progress={progress} ocrStatus={ocrStatus} parsedPages={parsedPages} /></div></div><RiskRow telemetry={telemetry} setSelectedEvent={setSelectedEvent} setView={setView} /><div className="lower-grid"><div className="panel activity-panel"><StreamPanel ocrStatus={ocrStatus} /></div><div className="panel prediction-panel"><PredictionPanel prediction={prediction} setPrediction={setPrediction} question={question} setQuestion={setQuestion} askPrediction={askPrediction} /></div></div></>
  }
  const navItems: [View, ReactNode, string][] = [['command', <Crosshair size={17} />, 'Command Center'], ['documents', <FileScan size={17} />, 'Documents'], ['embeddings', <Network size={17} />, 'Embedding Explorer'], ['prediction', <BrainCircuit size={17} />, 'Prediction Mode']]
  return <div className={`app-shell ${sidebarOpen ? '' : 'sidebar-collapsed'}`}><header className="topbar"><button className="sidebar-toggle" onClick={() => setSidebarOpen((open) => !open)} aria-label={sidebarOpen ? 'Collapse navigation' : 'Open navigation'}>{sidebarOpen ? <PanelLeftClose size={18} /> : <Menu size={18} />}</button><div className="brand-lockup"><div className="brand-mark">N°</div><div><div className="brand-title">NWIS</div><div className="brand-subtitle">NEARBY WELLS INTELLIGENCE</div></div></div><div className="top-search"><Search size={15} /><span>Search wells, events, formations…</span></div><div className="top-actions"><span className="online-pill"><i /> PIPELINE ONLINE</span><button aria-label="Notifications"><Bell size={17} /></button><button aria-label="Settings"><Settings2 size={17} /></button></div></header><div className="app-layout"><aside className="sidebar"><div className="sidebar-top"><span>WORKSPACE</span><button onClick={() => setSidebarOpen(false)} aria-label="Collapse sidebar"><PanelLeftClose size={15} /></button></div><nav>{navItems.map(([id, icon, label]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}>{icon}<span>{label}</span>{id === 'prediction' && <i className="nav-alert" />}</button>)}</nav><div className="sidebar-section"><span>ACTIVE WELL</span><button className="well-switch"><strong>{selectedWell}</strong><small>BARAIL · {telemetry.toLocaleString()} m</small><ChevronDown size={14} /></button></div><div className="sidebar-section"><span>QUICK ACTIONS</span><label className="sidebar-upload"><Upload size={15} /> Ingest document<input type="file" accept=".pdf,.png,.jpg,.jpeg,.tiff" onChange={handleUpload} /></label><button onClick={() => setView('prediction')}><Sparkles size={15} /> Ask NWIS</button></div><div className="sidebar-foot"><span><i className="online-dot" /> Local pipeline</span><small>DEMO DATASET · SYNTHETIC</small></div></aside><main className="main-content"><div className="page-heading"><div><span className="eyebrow">{view === 'command' ? 'FIELD OVERVIEW' : view === 'documents' ? 'DOCUMENT INTELLIGENCE' : view === 'embeddings' ? 'EVIDENCE GRAPH' : 'DECISION SUPPORT'}</span><h1>{view === 'command' ? 'Good morning, drilling team.' : view === 'documents' ? 'Make every report searchable.' : view === 'embeddings' ? 'See the memory of the field.' : 'Think one move ahead.'}</h1></div><span className="date-stamp">20 MAY 2025&nbsp;&nbsp; / &nbsp;&nbsp;SHIFT 02</span></div><div className="workspace">{renderView()}</div></main></div><div className="status-footer"><span><i className="online-dot" /> LOCAL PIPELINE ONLINE</span><span><FileText size={12} /> {uploadName}</span><span>ALL DATA STAYS ON DEVICE</span><CircleHelp size={13} /></div></div>
}

function PanelHeader({ icon, title, meta }: { icon: ReactNode; title: string; meta?: string }) { return <div className="panel-header"><span className="panel-title"><i>{icon}</i>{title}</span>{meta && <span className="panel-meta">{meta}</span>}</div> }
function DepthPanel({ telemetry }: { telemetry: number }) {
  return <>
    <PanelHeader icon={<Activity size={16} />} title="ACTIVE WELL" meta="A-17 / LIVE" />
    <div className="active-depth"><span>MD</span><strong>{telemetry.toLocaleString()} m</strong><b>FORMATION: BARAIL</b></div>
    <div className="depth-head"><span>FORMATION</span><span>LIVE LOG</span><span>TVD (m)</span></div>
    <div className="depth-chart">
      <div className="formation-column">
        <span>GIRUJ</span><span>PAB</span><span className="barail-upper">UPPER<br />BARAIL</span><span className="barail">BARAIL</span><span>LOWER<br />BARAIL</span><span>BASAL<br />SAND</span><span>PRE-CAMBRIAN<br />BASEMENT</span>
      </div>
      <div className="depth-log" aria-label="Live well log">
        <div className="gamma-line" />
        <div className="tvd-lines"><i /><i /><i className="hot" /><i /><i className="hot" /><i /><i /></div>
      </div>
      <div className="depth-labels"><span>2,000</span><span>2,200</span><span>2,400</span><span>2,600</span><span>2,800</span><span>3,000</span><span>3,200</span><span>3,400</span></div>
      <div className="depth-marker" style={{ top: `${Math.min(92, 29 + (telemetry - 2800) * .3)}%` }}><span>{telemetry.toLocaleString()} m</span></div>
    </div>
    <div className="chart-legend"><span><i className="line cyan-line" />GAMMA (API)</span><span><i className="line coral-line" />ROP (m/h)</span></div>
  </>
}
function PdfPage({ pages }: { pages: number }) { const canvasRef = useRef<HTMLCanvasElement>(null); const [page, setPage] = useState(1); useEffect(() => { let cancelled = false; (async () => { const pdf = await getDocument({ url: activePreviewUrl }).promise; const current = await pdf.getPage(page); const viewport = current.getViewport({ scale: 1.45 }); const canvas = canvasRef.current; if (!canvas || cancelled) return; const context = canvas.getContext('2d'); if (!context) return; canvas.width = viewport.width; canvas.height = viewport.height; await current.render({ canvas, canvasContext: context, viewport }).promise })().catch(() => undefined); return () => { cancelled = true } }, [page]); return <div className="pdf-canvas-shell"><div className="pdf-page-controls"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)}>← Previous</button><span>PAGE {page} OF {pages}</span><button disabled={page === pages} onClick={() => setPage((value) => value + 1)}>Next →</button></div><div className="pdf-page"><canvas ref={canvasRef} />{blocks.map((block, index) => <div key={block.id} className={`seg-box ${block.tone} ${index < 6 ? 'visible' : ''}`} style={{ left: `${block.x}%`, top: `${block.y}%`, width: `${block.w}%`, height: `${block.h}%` }}><span>{block.label}</span></div>)}</div></div> }
function DocumentPanel({ processing, progress, ocrStatus, parsedPages }: { processing: boolean; progress: number; ocrStatus: string; parsedPages: number }) { return <><PanelHeader icon={<FileScan size={16} />} title="DOCUMENT INTELLIGENCE" meta={processing ? 'PROCESSING' : 'INDEXED'} /><div className="document-stage"><div className="paper"><PdfPage pages={parsedPages} /></div></div><div className="document-footer"><span><i className="live-dot" /> {processing ? `PARSING PAGE 01 · ${progress}%` : `${ocrStatus} · ${parsedPages} PAGES`}</span><span>CONFIDENCE <b>0.93</b> <ChevronDown size={13} /></span></div></> }
function EmbeddingPanel({ selectedEvent, setSelectedEvent }: { selectedEvent: string; setSelectedEvent: (value: string) => void }) { return <><PanelHeader icon={<Network size={16} />} title="EVIDENCE EMBEDDING SPACE" meta="UMAP / 148 PASSAGES" /><div className="embedding-canvas large-canvas"><div className="embedding-axis horizontal" /><div className="embedding-axis vertical" /><span className="cluster-label label-loss">MUD LOSS</span><span className="cluster-label label-pressure">PRESSURE</span><span className="cluster-label label-pipe">STUCK PIPE</span><span className="cluster-label label-cement">CEMENTING</span>{embeddingPoints.map(([x, y, tone], index) => <button key={index} className={`embedding-point ${tone} ${index === 2 ? 'selected' : ''}`} style={{ left: `${x}%`, top: `${y}%` }} onClick={() => setSelectedEvent(tone === 'coral' ? 'Stuck pipe' : tone === 'amber' ? 'Formation pressure' : 'Partial returns')} aria-label={`Evidence point ${index + 1}`} />)}<div className="embedding-tooltip"><strong>{selectedEvent}</strong><span>12 related passages</span><small>A-08 · A-15 · A-17</small></div></div></> }
function StreamPanel({ ocrStatus }: { ocrStatus: string }) { return <><PanelHeader icon={<Zap size={16} />} title="LIVE PARSING STREAM" meta="LOCAL WORKER" /><div className="stream-list"><StreamItem time="NOW" icon={<FileText size={15} />} title="PDF + OCR extraction" detail={ocrStatus} tone="cyan" /><StreamItem time="NOW" icon={<Database size={15} />} title="Formation entity linked" detail={`${ddrRecord.formation} · 2,760–3,050 m · 0.93`} tone="cyan" /><StreamItem time="NOW" icon={<AlertTriangle size={15} />} title="Historical event matched" detail={`${ddrRecord.events[0].title} at ${ddrRecord.events[0].depth.toLocaleString()} m · A-08`} tone="amber" /><StreamItem time="NOW" icon={<BrainCircuit size={15} />} title="Embedding cluster updated" detail={`${ddrRecord.offsets.length} nearby well contexts indexed`} tone="violet" /></div></> }
function StreamItem({ time, icon, title, detail, tone }: { time: string; icon: ReactNode; title: string; detail: string; tone: string }) { return <div className="stream-item"><time>{time}</time><span className={`stream-icon ${tone}`}>{icon}</span><div><strong>{title}</strong><span>{detail}</span></div><ArrowUpRight size={13} /></div> }
function PredictionPanel({ prediction, setPrediction, question, setQuestion, askPrediction }: { prediction: boolean; setPrediction: (value: boolean) => void; question: string; setQuestion: (value: string) => void; askPrediction: (event: FormEvent) => void }) { return <><PanelHeader icon={<Sparkles size={16} />} title="PREDICTION MODE" meta="EVIDENCE-GROUNDED" />{!prediction ? <><p className="prediction-intro">Ask what the current trajectory means before you commit to the next operational decision.</p><form className="ask-form" onSubmit={askPrediction}><textarea value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="e.g. If we increase mud weight by 0.4 SG at Barail top, what could go wrong?" /><button type="submit"><Send size={15} /> ASK NWIS</button></form><div className="suggestion-row"><button onClick={() => setQuestion('What risks are likely in the next 100 m?')}>NEXT 100 M <ArrowDownRight size={13} /></button><button onClick={() => setQuestion('Compare this formation with A-08.')}>COMPARE A-08 <ArrowUpRight size={13} /></button></div></> : <div className="prediction-result"><div className="prediction-result-head"><span className="result-chip"><AlertTriangle size={13} /> ELEVATED RISK</span><button onClick={() => setPrediction(false)} aria-label="Close prediction"><X size={14} /></button></div><h3>Partial losses are the leading concern.</h3><p>At Barail top, the proposed increase may improve overbalance but could worsen losses in the fractured sandstone interval.</p><div className="evidence-list"><span><i />A-08 · Partial returns at 2,790 m</span><span><i />A-15 · Mud-weight increase preceded losses</span></div><div className="recommendation"><b>CHECK BEFORE PROCEEDING</b><span>Confirm flow-out trend, ECD margin, and loss rate over the next 15 minutes.</span></div></div>}</> }
function RiskRow({ telemetry, setSelectedEvent, setView }: { telemetry: number; setSelectedEvent: (value: string) => void; setView: (view: View) => void }) { return <section className="risk-row"><div className="risk-label"><AlertTriangle size={25} /><div><small>LIVE DECISION SUPPORT</small><strong>RISK WATCH</strong></div></div><RiskCard label="MUD LOSS" value="72%" trend="RISING" tone="critical" icon="◌" onClick={() => setSelectedEvent('Partial returns')} /><RiskCard label="STUCK PIPE" value="41%" trend="RISING" tone="critical" icon="⌁" onClick={() => setSelectedEvent('Stuck pipe')} /><RiskCard label="WELLBORE INSTABILITY" value="28%" trend="STEADY" tone="warning" icon="◇" onClick={() => setSelectedEvent('Wellbore instability')} /><RiskCard label="FORMATION PRESSURE" value="35%" trend="STEADY" tone="warning" icon="◉" onClick={() => setSelectedEvent('Formation pressure')} /><div className="alerts-card"><div><span className="alert-count">ALERTS (2)</span><span>09:41&nbsp;&nbsp; Partial Returns @ {telemetry.toLocaleString()} m</span><span>09:35&nbsp;&nbsp; High Flow Deviation</span></div><button onClick={() => setView('prediction')}>VIEW ALL <ArrowUpRight size={13} /></button></div></section> }
function RiskCard({ label, value, trend, tone, icon, onClick }: { label: string; value: string; trend: string; tone: Tone; icon: string; onClick: () => void }) { return <button className={`risk-card ${tone}`} onClick={onClick}><span className="risk-icon">{icon}</span><div><small>{label}</small><strong>{value}</strong><span className="risk-trend">TREND&nbsp; <b>{trend}</b></span></div><span className="sparkline">⌁⌁⌁</span></button> }
